version: "3.8"

services:
  tensorflow:
    build: .
    container_name: my.image.name:latest
    stdin_open: true
    tty: true
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - .:/home/app:rw
    deploy:
      resources:
        reservations:
          devices:
            # # Allow all GPUs
            # - capabilities: [gpu]

            # Allow some GPUs 
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
